### ISSUE TITLE
pembatas antara Email & Telepon Desa di bagian Footer

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#10]
tambahkan pembatas ( | ) diantara teks Email dengan Telepon dibagian bawah dan ditambahkan tulisan Tlp. pada teks telepon misalnya menjadi:

**DESA NATAI RAYA**
Jl. Pangkalan Lima IQ, Pangkalan Bun
Kecamatan Arut Selatan Kabupaten Kotawaringin Barat Provinsi Kalimantan Tengah Kode Pos 74117

E-mail: natai.raya@mail.com | Tlp. 0856123456789

**Comment by ariandii** [comment]
atau dibawah saja? dengan pertimbangan jika dibuka melalui mobile view nya supaya seimbang.

**Comment by hasap86** [comment]
> atau dibawah saja? dengan pertimbangan jika dibuka melalui mobile view nya supaya seimbang.

Setuju mas

**Comment by ariandii** [comment]
Sudah dicommit ke master.
