### ISSUE TITLE
Login admin dan layanan mandiri

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tema-natra#104]
Tema Natra tidak memiliki tombol login, sehingga menu statis digunakan untuk login, yg secara default ditempatkan di menu paling kanan. Namun, ada pengguna yang berulangkali membuat issue untuk menghapuskan menu login bawaan tersebut dengan alasan ingin menempatkan di lokasi sendiri. 

Penghapusan dan penambahan menu login ini telah dilakukan beberapa kali, karena memang tidak semua pengguna menginginkan menu login tersebut ada di tempat yg tidak bisa diubah. Sedangkan kalau menu login itu tidak ada, pengguna lain bingung cara untuk login.

Sebaiknya sistem tidak melakukan perubahan menu login ini pada migrasi ataupun diatur langsung oleh tema natra secara mati. Yaitu sistem tidak menghapus atau menambah menu login secara otomatis. Biarkan pengguna sendiri yg menentukan. 

Karena tema Natra tidak memiliki tombol login, alternatifnya adalah:

1. buat tombol login admin dan layanan mandiri di luar menu; atau 
2. sediakan menu login hanya pada awal saja. Yaitu, pastikan di contoh data awal disediakan menu statis, di mana menu tersebut tidak terhapus pada waktu kosongkan database. Kemudian terserah pada pengguna untuk menghapus atau memindahkan. Karena menu statis ini ada pada contoh data awal, menu itu juga akan tampil di tema esensi atau lainnya. Jika menu itu tidak diinginkan, pengguna dapat menghapus saja.

Pilihan 1 di atas lebih aman dan tidak mempengaruhi tema lain yg memiliki tombol login di luar menu.

Konsultasi dengan @ariandii cara terbaik untuk menyediakan tombol login admin dan mandiri untuk tema Natra di luar menu.

**Comment by tobagus6911** [comment]
sekalian sama login kehadiran

**Comment by ariandii** [comment]
Posisi tombol pindah di sini?

<img width="960" alt="screenshot_215" src="https://user-images.githubusercontent.com/46939846/161735433-802f3ac2-9365-4100-804c-3d78024ed014.png">

**Comment by eddieridwan** [comment]
Perhatikan bahwa Rekam Kehadiran hanya berlaku di gawai Rekam Kehadiran. Dan di gawai itu, hanya digunakan untuk Rekam Kehadiran, tidak dimaksudkan untuk tujuan lain. Jadi tidak tepat memasang tombol Rekam Kehadiran di tema web.

**Comment by ariandii** [comment]
artinya apakah desa yang ingin buka halaman kehadiran, akan ketik manual diakhir URL /kehadiran

**Comment by eddieridwan** [comment]
Artinya, gawai yg dikhususkan untuk rekam kehadiran, misalnya tablet atau HP, akan selalu terbuka ke login rekam kehadiran. Karena fungsinya hanya untuk rekam kehadiran. Gawai itu misalnya dipasang di dinding masuk ruang utama kantor desa bagi perangkat desa.

**Comment by ariandii** [comment]
Dengan input IP jaringan kantor yg muncul ke pengaturan kehadiran, maka seluruh Aparatur Desa bisa lakukan rekam kehadiran dari HP mereka masing masing selama dalam 1 jaringan kantor.

mereka membuka web desa dari hp dan klik tombol halaman rekam kehadiran tersebut.

siap masuk untuk klik hadir atau keluar.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tema-natra/pull/119
