### ISSUE TITLE
Konten di versi mobile dilebarin lagi proporsional dengan header

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#11]
Pada bagian konten terlalu ke tengah sehingga menjadi menyempit, mungkin bisa disamakan dengan bagian header marginnya.

![mobile-view-konten-lebarin](https://user-images.githubusercontent.com/45263721/58140584-f5471f00-7c69-11e9-92d0-d621d97bcc23.jpg)

**Comment by ayiroger** [comment]
Untuk tampilan mobile tidak bisa memilih sub menu,karena waktu kita klik judul menu langsung mengarah ke sebuah link. Menurut saya sebaiknya di setiap judul menu jangan di buat link.

**Comment by afa28** [comment]
> Untuk tampilan mobile tidak bisa memilih sub menu,karena waktu kita klik judul menu langsung mengarah ke sebuah link. Menurut saya sebaiknya di setiap judul menu jangan di buat link.

Sesuaikan saat pembuatan parrent menu di admin, untuk parrent beri link = #

**Comment by ayiroger** [comment]
Kalau kita edit file menu nav nya dmn letaknya mas

**Comment by afa28** [comment]
> Kalau kita edit file menu nav nya dmn letaknya mas

partial/menu_head.php, lakukan penyesuaian mulai dr baris 20

**Comment by ayiroger** [comment]
Ok siap,mksh ilmunya mas
