### ISSUE TITLE
Saat Loading Web Widget Aparatur Desa muncul

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#12]
Pada saat kondisi loading web widget Aparatur Desa ikut muncul, seharusnya blank semua saat kondisi loading

![loading-widget-muncul](https://user-images.githubusercontent.com/45263721/58355100-80f4c180-7e9d-11e9-9ab7-b0f2eedb32da.jpg)

**Comment by demisisri** [comment]
Di website kami selain widget aparatur desa, widget peta desa (openstreetmap) juga ikut muncul saat loading

**Comment by haqi89** [comment]
Sekarang selain data desa loader tidak muncul,,

**Comment by ilhamoperanda** [comment]
aparatur desa tidak muncul, data nya ke get dari db tapi ga show di front end.

![web](https://user-images.githubusercontent.com/12399194/92240842-7110bd80-eee7-11ea-98fa-08d260fa037e.PNG)

**Comment by ariandii** [comment]
sudah disesuaikan loading tanpa icon loader
