### ISSUE TITLE
[Bug] error pada saat pengaturan covid desa di aktifkan

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/tema-natra#124]
Muncul Error ketika mengaktifkan feed covid desa di pengaturan 
Admin Web -> Pengaturan -> lalu pada Covid Desa dipilih menjadi **Ya**
<img width="515" alt="image" src="https://user-images.githubusercontent.com/59082428/181747558-9ed65a4e-7c66-442e-9974-f7bc5152b76c.png">

lalu pilih pengaturan themes menjadi **netra**  caranya masuk ke 
Pengaturan -> aplikasi -> Web Theme -> pilih menjadi **netra**

lalu buka ke homepage atau tampilan depan website maka akan muncul error seperti ini : 
<img width="814" alt="image" src="https://user-images.githubusercontent.com/59082428/181748006-1532bbeb-4c8b-47b0-9071-9dccf4e3b247.png">

**Comment by yogiperdana** [comment]
Setelah dicek berjalan normal mas @vickyrolanda . Pastikan temanya sudah ditambahkan terlebih dahulu

**Comment by yogiperdana** [comment]
![image](https://user-images.githubusercontent.com/14155050/181888037-0fedad10-03d8-4d3e-90b5-5b3040444ebc.png)

**Comment by yogiperdana** [comment]
Dengan demikian apakah bisa ditutup mas?

**Comment by vickyrolanda** [comment]
baik mas yogi, tpi ini akan saya masukkan ke list analisa saya terkain API yang tidak di pakai & terkait tema yang di vendor yang harus di update terbaru.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/tema-natra/pull/125
