### ISSUE TITLE
Sesuaikan Style Ganti Password pada Layanan Mandiri

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#15]
Saat ini Style Layanan Mandiri untuk Ganti Password saat Login Layanan Mandiri masih menggunakan Style Lama, belum disesuikan dengan tema. Sebaiknya disamakan seperti Style Login

**Comment by ariandii** [comment]
dimana ada fitur ganti password Layanan Mandiri? bisa tampilkan screenhotnya?

**Comment by hasap86** [comment]
coba login layanan mandiri untuk salah satu warga, nanti keliatan fitur Ubah Password dibawah menu Layanan Mandiri
![Screenshot_20190618-045356~2](https://user-images.githubusercontent.com/45263721/59639461-8afc9e00-9185-11e9-8fc3-5f5c7fec884f.png)

**Comment by ariandii** [comment]
Sudah dicommit ke master.

**Comment by hasap86** [comment]
Posisi Ubah Pin yang sekarang koq jadi pindah ke atas ya, harusnya di bawah Menu Layanan Mandiri

**Comment by ariandii** [comment]
Dengan pertimbangan agar lebih terlihat jika pin belum diganti.
