### ISSUE TITLE
Tambah Nilai untuk Anggaran & Pendapatan

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#16]
Tambahkan nilai untuk 

- SILPA Tahun Sebelumnya
- Pendapatan Lain-lain  
- Bantuan Provinsi

pada Anggaran Tahun 2019 & Pendapatan Tahun 2018

**Comment by ariandii** [comment]
- untuk SILPA tahun sebelumnya sudah ada dengan istilah Penerimaan Pembiayaan.

- Pendapatan Lain-Lain sejak awal sudah tersedia.

**Comment by hasap86** [comment]
apa lebih baik dirubah Istilahnya menjadi SILPA Tahun Sebelumnya?

Pendapatan Lain-lain belum ada, 
![Screenshot_20190618-050352~2](https://user-images.githubusercontent.com/45263721/59640020-132f7300-9187-11e9-8590-c0522b5ea145.png)

**Comment by ariandii** [comment]
> * untuk SILPA tahun sebelumnya sudah ada dengan istilah Penerimaan Pembiayaan.
> * Pendapatan Lain-Lain sejak awal sudah tersedia.

Maaf, Pendapatan Lain-Lain di tahun berjalan apakah sudah tersedia?

**Comment by ariandii** [comment]
Sudah dicommit ke master.
