### ISSUE TITLE
Lengkapi Title Browser di Homepage

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#18]
sebaiknya untuk Title Web Browser yang saat ini hanya menampilkan nama desa dilengkapi dengan nama Kecamatan Kabupaten dan Provinsi, karena kalo title browser hanya desa saja ada kemungkinan ada beberapa desa yang sama sehingga ketika dicari di mesin pencari bisa saja bukan desa yang dimaksud.

misalnya jadi begini: Sistem Informasi Desa Natai Raya Kecamatan Arut Selatan Kabupaten Kota Waringin Barat, Kalimantan Tengah

**Comment by ariandii** [comment]
untuk title sebaiknya menggunakan kalimat singkat dan sederhana, untuk info yang lebih lenhkap ada deskripsi yang sudah dibuat pada meta.php

**Comment by hasap86** [comment]
baik mas, sip
