### ISSUE TITLE
Warna Widget Artikel

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#19]
![warna-konten-artikel-widget](https://user-images.githubusercontent.com/45263721/59725961-f3b54a80-9259-11e9-9689-e67177621504.jpg)

saat ini warna untuk kontek widget Artikel lebih mencolok pada tanggal posting sedangkan judul artikelnya agak redup, mungkin lebih baik warna tanggal posting menggunakan warna judul artikel dan judul artikel agak hitaman warnanya seperti konten lainnya.

**Comment by ariandii** [comment]
untuk warna kembali kepada selera masing-masing, silakan modifikasi pada widget tersebut.

contoh seperti salah satu web desa berikut:

![Screenshot_2019-06-19-15-43-48-42](https://user-images.githubusercontent.com/46939846/59750572-35b9ad00-92a9-11e9-9e06-3f7dc3260a31.png)

**Comment by hasap86** [comment]
okesiap...
