### ISSUE TITLE
Ukuran layout pada apb desa tidak seragam

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/tema-natra#22]
Untuk layout pada apb desa sebaiknya diseragamkan.
`Berikut saya lampirkan contoh yang diharapkan`

![image](https://user-images.githubusercontent.com/10989147/63575973-7d182e80-c5b5-11e9-8200-71424c5f40b9.png)

**Comment by ariandii** [comment]
Sudah dicommit ke master.
