### ISSUE TITLE
eror komentar kode selalu salah, silahkan ulangi lagi

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/tema-natra#26]
![9](https://user-images.githubusercontent.com/57661283/70124587-b463a480-16a7-11ea-8ff0-0ae4fbbeb7a4.png)

mohon solusi komentar pengunjung tidak bisa masuk ke administrator. selalu muncul keterangan kode anda salah, silahkan ulangi lagi.

padahal kode sudah benar, sudah dicoba berkali-kali selalu muncul pesan gtu.

**Comment by ariandii** [comment]
Lancar saja pak, tidak ada kendala.

![image](https://user-images.githubusercontent.com/46939846/70369450-0dbc1580-18ec-11ea-8f08-ee6df6aef0b6.png)

Atau coba download ulang tema nya di
https://github.com/OpenSID/tema-natra/archive/master.zip
