### ISSUE TITLE
Munculkan Thumbnail Gambar di artikel yang dijadikan headine

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#3]
sebaiknya di tampilan artikel yang dijadikan headline dimunculkan gambar di sebelah kiri artikel dengan ukuran proporsional dari gambar aslinya.

**Comment by ariandii** [comment]
Saya rasa ini sudah diterapkan sejak rilis awal pak.

![image](https://user-images.githubusercontent.com/46939846/57971677-3ebe1280-79bb-11e9-916f-d792569308cc.png)

**Comment by hasap86** [comment]
ow ternyata saya malah insert gambarnya di artikelnya bukan di inputan gambarnya, tapi ini masih ada bug untuk gambar yg tinggi jadi keluar jalur

![gambar-headline-bug-tinggi](https://user-images.githubusercontent.com/45263721/57971896-4c28cc00-79be-11e9-9a9f-dd768108fe35.jpg)

**Comment by ariandii** [comment]
Sudah dicommit ke master.
