### ISSUE TITLE
Informasi Publik

### ISSUE THREAD

**Issue by afa28** [OpenSID/tema-natra#30]
1. Tabel tidak responsive untuk tampilan mobile
2. Muncul 5 error di console

![Untitled](https://user-images.githubusercontent.com/57283157/75110207-e6105a00-565d-11ea-9707-3a5585d924f9.png)

**Comment by ariandii** [comment]
saya coba, responsive saja pak. mohon petunjuk.

![up](https://user-images.githubusercontent.com/46939846/75235405-c0668a80-57ee-11ea-973c-7698715af888.png)
