### ISSUE TITLE
Detail Agenda

### ISSUE THREAD

**Issue by afa28** [OpenSID/tema-natra#31]
Saat menampilkan detail agenda, waktu, lokasi dan koordinator di muncul.

Solusi : https://github.com/OpenSID/OpenSID/pull/2619

**Comment by ariandii** [comment]
belum bisa diterapkan ke tema natra, sebab branch OpenSID untuk file donjo-app/controllers/First.php  dan file donjo-app/models/First_artikel_m.php belum disesuaikan.

**Comment by ariandii** [comment]
Berikut hasil penerapan script di atas.

![up](https://user-images.githubusercontent.com/46939846/75235146-5c43c680-57ee-11ea-861f-18820cf2de9e.png)

**Comment by afa28** [comment]
Biar lebih menarik pqk, coba simpan di atas isi artikel. Tiap point beri icon.

**Comment by ariandii** [comment]
Berikut hasil tampilannya jika diterapkan ke tema natra dengan menggunakan branch OpenSID saat ini.
![image](https://user-images.githubusercontent.com/46939846/75361152-73b3aa00-58e9-11ea-82ba-a2f2840aa8c5.png)

**Comment by afa28** [comment]
> Berikut hasil tampilannya jika diterapkan ke tema natra dengan menggunakan branch OpenSID saat ini.
> 
> dan saya lupa menerapkan seperti hasil script di atas. TT
> 
> ![image](https://user-images.githubusercontent.com/46939846/75361152-73b3aa00-58e9-11ea-82ba-a2f2840aa8c5.png)

Kok beda ya hasilnya 🤣🤣🤣

**Comment by ariandii** [comment]
iya, karena yang atas tadi untuk file donjo-app/controllers/First.php dan file donjo-app/models/First_artikel_m.php sudah saya sesuaikan pak. cuma lupa caranya, cpanel terlanjur git pull.

**Comment by afa28** [comment]
Sy fork pak @ariandii , spa tau bisa bantu2 kembangkan.

**Comment by ariandii** [comment]
sudah di commit ke master, dengan tampilan sebderhana.
https://github.com/OpenSID/tema-natra/commit/3d9eb9df2f3142e3ec4a419553d514dfef3957a8
