### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by a241ni** [OpenSID/tema-natra#33]
halo pak cara menampilkan Grafik Bar APBDesa gimana ya ?milik saya tidak muncul
[https://prnt.sc/r7r4gg](url)

**Comment by ariandii** [comment]
cobe edit file partials/footer_top.php

baris pertama ganti dengan <?php $this->load->view($folder_themes . '/partials/apdes.php') ?>

Apakah muncul?

**Comment by a241ni** [comment]
done, makasih om sangat membantu

**Comment by ariandii** [comment]
Sudah dicommit ke master. Terima kasih.
