### ISSUE TITLE
Tambah Slider Lain

### ISSUE THREAD

**Issue by ronisuhendra** [OpenSID/tema-natra#37]
### Bagaimana alurnya sampai muncul masalah?
 Tolong Tambahkan Slider lain lagi untuk di bawah  Teks Berjalan 

### Seperti apa yang diharapkan?
Jadi Slider Atas Untuk Galeri/ Informasi   ....Dan Slider baru di bawah Teks Berjalan Untuk Berita Terbaru /Terpilih

### Apa yang terjadi?
![slider](https://user-images.githubusercontent.com/63826950/79521670-ec321e00-8083-11ea-9086-c5d0664fe09e.png)

Jadi Untuk Pengunjung lihat Berita Terbaru Atau Terpilih Tidak Usah Scroll Ke bawah Di Slider Sudah Ada

**Comment by ariandii** [comment]
Saat ini yang diterapkan OpenSID adalah 1 kesatuan antara slider yang bersumber dari Gallery maupun Slider yang bersumber dari Artikel.
