### ISSUE TITLE
Penggunaan variabel config_item untuk menampilkan covid

### ISSUE THREAD

**Issue by ericksuryadinata** [OpenSID/tema-natra#43]
Penggunaan variabel config_item yang benar yang mana ?

Di core sistem OpenSID menggunakan $config['provinsi_covid'] 

Tetapi di tema natra menggunakan config_item('covid_provinsi'), yang menyebabkan tidak munculnya data covid

Di tema klasik saya cek menggunakan config_item('provinsi_covid')

**Comment by eddieridwan** [comment]
Yg benar `provinsi_covid`. Boleh menggunakan `$config[]` atau` config_item()`. Tapi mungkin ada baiknya diseragamkan.

**Comment by ariandii** [comment]
sudah dicommit ke master untuk diseragamkan.
