### ISSUE TITLE
Arrow Kiri & Kanan disesuaikan

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#5]
![arrow-transparan-left-right](https://user-images.githubusercontent.com/45263721/57972780-4edcee80-79c9-11e9-8aab-53e543112668.jpg)

tombol geser kiri dan kanan disesuaikan dengan menyesuaikan tombol kiri mentok ke gambar kiri dan tombol kanan mentok di gambar bagian kanan, serta di kasih transparan supaya gambar bisa terlihat.

**Comment by ariandii** [comment]
Sudah dicommit ke master,

Saat ini tampilan widget aparatur desa sudah disesuaikan dengan menerapkan library cycle2.

**Comment by hasap86** [comment]
mas yg sekarang tombol kiri kanannya malah ilang yah? baiknya tetep di pertahankan tapi disesuaikan dengan desain yg sekarang, lebih tipis tanpa background kotaknya.

**Comment by ariandii** [comment]
Pertimbangannya seperti yang tercantum pada postingan di bawah ini pak, saya menyesuaikan saja.

https://m.facebook.com/story/graphql_permalink/?graphql_id=UzpfSTU2MTI3MjgyMzpWSzoxMjEwNzUwMTYyNDIzMjk2
