### ISSUE TITLE
widget agenda tidak tampil pada sidebar tema-natra

### ISSUE THREAD

**Issue by anthon055** [OpenSID/tema-natra#50]
dear mas ariandi,
saya pengguna baru openDesa, saat ini sudah menggunakan 20.06 dengan thema natra 4.1.9
namun saya mengalami kendala ketika ingin menampilkan widget agenda pada sidebar,
padahal status di pengaturan widget sudah aktif,
sementara jika menggunakan tema bawaan (klasik) widget agenda tersebut dapat tampil

bagian manakah pada thema yang harus saya sesuaikan ? 
demikian, sangat kami nantikan pencerahannya. 
tks
![image](https://user-images.githubusercontent.com/22672186/83982414-ba855700-a950-11ea-8344-f4b4bdd29129.png)
seharusnya tampil di sini :
![image](https://user-images.githubusercontent.com/22672186/83982436-e0126080-a950-11ea-9825-1a8544d52ec6.png)

**Comment by afa28** [comment]
> dear mas ariandi,
> saya pengguna baru openDesa, saat ini sudah menggunakan 20.06 dengan thema natra 4.1.9
> namun saya mengalami kendala ketika ingin menampilkan widget agenda pada sidebar,
> padahal status di pengaturan widget sudah aktif,
> sementara jika menggunakan tema bawaan (klasik) widget agenda tersebut dapat tampil
> 
> bagian manakah pada thema yang harus saya sesuaikan ?
> demikian, sangat kami nantikan pencerahannya.
> tks
> ![image](https://user-images.githubusercontent.com/22672186/83982414-ba855700-a950-11ea-8344-f4b4bdd29129.png)
> seharusnya tampil di sini :
> ![image](https://user-images.githubusercontent.com/22672186/83982436-e0126080-a950-11ea-9825-1a8544d52ec6.png)

Silahkan buat issuenya di https://github.com/OpenSID/tema-natra

**Comment by ariandii** [comment]
Sudah dicommit ke master. Terima kasih.
