### ISSUE TITLE
Grafik tidak tampil 

### ISSUE THREAD

**Issue by ajhojie** [OpenSID/tema-natra#51]
Grafik batang dan grafik lingkaran tidak tampil di bagian statistik

**Comment by ariandii** [comment]
Saya cek, muncul saja grafiknya.

![image](https://user-images.githubusercontent.com/46939846/87569087-d965ce80-c6f0-11ea-9f5c-ffe1d16db08b.png)

**Comment by ajhojie** [comment]
Di saya kok tidak tampil?
![Web](https://user-images.githubusercontent.com/65651345/87627858-e4a11480-c759-11ea-88d8-b53cf77c2299.jpg)

**Comment by ariandii** [comment]
silakan update opensid dan update tema nya.
