### ISSUE TITLE
Data Demografi Berdasar Populasi Per Wilayah blank

### ISSUE THREAD

**Issue by MUHAMMADRANGSEL** [OpenSID/tema-natra#54]
Menu Statis untuk Data Demografi Berdasar Populasi Per Wilayah tampilan blank ditampilan website
![image](https://user-images.githubusercontent.com/25834335/91463707-49ee3680-e8be-11ea-91e3-be5c6f98703d.png)

Harapannya Data Demografi Berdasar Populasi Per Wilayah tidak blank seperti sebelumnya

**Comment by afa28** [comment]
> Menu Statis untuk Data Demografi Berdasar Populasi Per Wilayah tampilan blank ditampilan website
> ![image](https://user-images.githubusercontent.com/25834335/91463707-49ee3680-e8be-11ea-91e3-be5c6f98703d.png)
> 
> Harapannya Data Demografi Berdasar Populasi Per Wilayah tidak blank seperti sebelumnya

Sudah sy coba, yg bermasalah ada di tema natra. Coba gunakan tema standar dan kemudian bandingkan dgn tema natra.

**Comment by MUHAMMADRANGSEL** [comment]
masalahnya di file wilayah yang ada di folder partials, saya copy paste scrip yang dari thema cosmos berjalan normal, seperti gambar dibawah ini
![image](https://user-images.githubusercontent.com/25834335/94825449-cbdefb80-0438-11eb-8167-e109210ddd0c.png)

**Comment by ullima-ellina** [comment]
saya tambahin style="width: 100%;" di 
<div class="table-responsive" style="width: 100%;">

**Comment by ariandii** [comment]
sudah dicommit ke master
