### ISSUE TITLE
Daftar Menu Dinamis (Kategori) pada web tidak muncul

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/tema-natra#56]
Daftar menu dinamis (kategori) di web tidak tampil, hanya berupa simbol-simbol panah saja. Seperti gambar dibawah ini.

![photo_2020-11-17_15-44-57](https://user-images.githubusercontent.com/32125282/99366955-e63b3e80-28eb-11eb-9fd3-42c457d98eb7.jpg)

Ini terjadi pada opensid premium V.20.11 dan opensid biasa 20.11

**Comment by afa28** [comment]
Usahakan testing menggunakan tema bawaan dan coba dilakukan di situs demo agar yg lain jg bisa mengecek.

Jika di situs demo lancar, silahkan hubungi pembuat tema untuk menyelesaikan dgn update OpenSID terbaru.

**Comment by ariandii** [comment]
Sudah di commit ke master.
