### ISSUE TITLE
Data Informasi Publik Tidak Tampil pada web

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/tema-natra#57]
Data dokumen informasi publik (menu statis informasi publik)  tidak tampil pada web.
dan menunjukan error pada gambar berikut.
![in](https://user-images.githubusercontent.com/32125282/99367574-b6d90180-28ec-11eb-8351-a841a6332ffc.jpg)

Daftar informasi publik kosong.

**Comment by afa28** [comment]
Usahakan testing menggunakan tema bawaan dan coba dilakukan di situs demo agar yg lain jg bisa mengecek.

Jika di situs demo lancar, silahkan hubungi pembuat tema untuk menyelesaikan dgn update OpenSID terbaru.

**Comment by ariandii** [comment]
Setelah di test, data Informasi Publik tampil sebagaimana mestinya.
