### ISSUE TITLE
Daftar Bantuan Tidak Tampil di Web

### ISSUE THREAD

**Issue by HerryWanda** [OpenSID/tema-natra#58]
Masalah : Daftar bantuan tidak tampil/ kosong

namun untuk jenis data bantuan dan pie chart nya tampil.
Gambar sebagai berikut : 
![ba](https://user-images.githubusercontent.com/32125282/99368011-3f57a200-28ed-11eb-92ce-d30a05dc5509.jpg)

Pesan error : datatables warning (sama dengan error daftar informasi publik) tidak tampil

**Comment by afa28** [comment]
Usahakan testing menggunakan tema bawaan dan coba dilakukan di situs demo agar yg lain jg bisa mengecek.

Jika di situs demo lancar, silahkan hubungi pembuat tema untuk menyelesaikan dgn update OpenSID terbaru.

**Comment by ariandii** [comment]
Setelah di test, Daftar Penerima Bantuan Keluarga tampil sebagaimana mestinya.
