### ISSUE TITLE
Menu Kategori Tidak Muncul Pada Update 20.12

### ISSUE THREAD

**Issue by mr703** [OpenSID/tema-natra#59]
Menu Kategori Tidak Lagi Muncul di Thema Natra Setelah Opensid Update 20.12,,

**Comment by afa28** [comment]
> Menu Kategori Tidak Lagi Muncul di Thema Natra Setelah Opensid Update 20.12,,

Silahkan update temanya, ada perubahan struktur pd pemanggilan kategori.
Jika sudah diupdate dan masilh bermasalah, silahakan dibuat isseunya di https://github.com/OpenSID/tema-natra atau hubungi pengembang tema untuk diperbaiki.
