### ISSUE TITLE
Logo di bagian tengah status loading

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#6]
![logo-loading](https://user-images.githubusercontent.com/45263721/57972839-fc500200-79c9-11e9-8d74-d3fe6ebcb79a.jpg)

kasih gambar logo di tengah animasi loading...

**Comment by ariandii** [comment]
Animasi tersebut bisa diganti sesuai keinginan pada folder natra/assets/css/images/status.gif
