### ISSUE TITLE
Table responsive data demograsi tidak muncul versi desktop

### ISSUE THREAD

**Issue by ilamazuliaf** [OpenSID/tema-natra#64]
Saat mengakses via desktop tidak muncul
<img width="1280" alt="Screen Shot 2021-01-09 at 01 34 20" src="https://user-images.githubusercontent.com/31075119/104052189-e8e74f80-521b-11eb-96b4-cf9d0af19f79.png">

sedangkan versi mobile aman
<img width="1280" alt="Screen Shot 2021-01-09 at 01 35 10" src="https://user-images.githubusercontent.com/31075119/104052499-6743f180-521c-11eb-97e4-3b9fbe3638e6.png">

Seharusnya dikedua versi sama-sama tampil dan responsive.

**Comment by ariandii** [comment]
Terima kasih, sudah dicommit ke master.
