### ISSUE TITLE
Hilangkan Menu Login Secara Default

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#66]
Saat ini menu login default dimunculkan di menu, mungkin diantara pengguna tidak ingin menampilkan link menu Login untuk menghindari sesuatu hal.

untuk menambahkan Menu Login bisa melalui Link Eksternal sendiri sendiri.

Terimakasih

**Comment by ariandii** [comment]
Terima kasih, sudah dicommit ke master.
