### ISSUE TITLE
Terjadi Error Ketika Menampilkan Menu bantuan

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/tema-natra#67]
Saat akan membuka menu bantuan keluarga, muncul notif sbb:

![bug_bantuan](https://user-images.githubusercontent.com/39736008/105480660-9bb5b400-5cd8-11eb-89b6-d119168c7519.png)

**Comment by ariandii** [comment]
Terima kasih. Sudah di commit ke master.
