### ISSUE TITLE
Pindahkan Kotak Pencarian

### ISSUE THREAD

**Issue by mizwaruddin** [OpenSID/tema-natra#68]
Ketika menu terus bertambah, maka posisi kotak pencarian akan pindah ke bawah menu. Hal ini menjadikan bagian menu tidak enak dipandang.

![bug_natra](https://user-images.githubusercontent.com/39736008/105484189-868f5400-5cdd-11eb-9296-3c1aa7c0ae8d.png)

**Comment by ariandii** [comment]
Terima kasih, sudah dicommit ke master.
