### ISSUE TITLE
Tampilan Statistik Desa kurang proporsioanl

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#7]
![tampilan-statistik-kurang-proporsional](https://user-images.githubusercontent.com/45263721/57972929-150ce780-79cb-11e9-9545-0b04f1733215.jpg)

Tampilan antar icon statistik kurang rapi dan proporsional, pengaturan jarak harus di sesuaikan lagi agar lebih baik dari segi tampilan

**Comment by ariandii** [comment]
Keenam image statistik desa dapat disesuaikan dan diganti melalui folder /natra/images

**Comment by hasap86** [comment]
ok, tapi untuk jarak teks ke image tiap tiap gambarnya harus dari css nya ya

**Comment by ariandii** [comment]
itu tidak ada teks, image keseluruhan.
