### ISSUE TITLE
Link Daftar Agregasi Analisis Desa Tidak Tampil

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#74]
Saat ini tidak bisa membuka link Analisis dengn url **/data_analisis** di web, tapi jika menggunakan tema hakadewa bisa terbuka.
(HTTP ERROR 500)

pembuatan linknya
![analisis](https://user-images.githubusercontent.com/45263721/111851602-66c78580-8946-11eb-8efb-203590c51cc7.jpg)

**Comment by eddieridwan** [comment]
Sdh dicommit ke `master` melalui https://github.com/OpenSID/tema-natra/pull/75
