### ISSUE TITLE
Mengganti Favicon dan Penambahan Sumber Pendapatan

### ISSUE THREAD

**Issue by Jehamahdan** [OpenSID/tema-natra#8]
1. Bagaimana Cara mengganti Favicon bawaan Tema Natra di ganti sesuai logo desa/kabupaten masing2..?

2. Bagaimana cara menambahkan Sumber Dana pada Anggaran Pendapatan dan Belanja di apbdes.php? misal ada yang di sebut Bantuan Keuangan Kabupaten (PBK), Bantuan Keuangan Provinsi (PBP)..

**Comment by ariandii** [comment]
1. Silakan baca panduan pada wiki.

2. Silakan baca keterangan pada bagian bawah readme.md
