### ISSUE TITLE
Tampilan pada Halaman Pembangunan Berantakan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/tema-natra#87]
Ketika item kegiatan lebih dari satu dan deskripsi kegiatan maupun gambar ukurannya berbeda, terlihat tampilannya menjadi berantakan, seperti berikut:

![Tampilan pada modul pembangunan](https://user-images.githubusercontent.com/68048807/151502810-769aa3dd-acf8-4798-b29d-90ffbfde6e80.PNG)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/tema-natra/pull/102
