### ISSUE TITLE
Bug/error: padding/margin pada demo umum vs premium

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/tema-natra#88]
### Jelaskan error yg dialami

padding / margin di tema Natra berbeda?

https://berputar.opensid.or.id/
![image](https://user-images.githubusercontent.com/2387514/151750165-931e592f-1493-4a8d-ac69-857cf392054a.png)

https://demo.opensid.or.id/
![image](https://user-images.githubusercontent.com/2387514/151750117-0f5ffc39-efea-48d4-82d6-92e7ff9430ed.png)

### Cara untuk mereplikasi errornya

akses kedua DEMO dari Premium & umum
https://berputar.opensid.or.id/
https://demo.opensid.or.id/

### Hasil yg diharapkan

Jika keduanya menggunakan template yang sama, semestinya hasilnya juga sama

### Tangkapan layar dan log error

lihat atas

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

*

### Tema Yang Digunakan

Natra 4.5

**Comment by totoprayogo1916** [comment]
masalahnya ada di style.css ..

untuk yang di branch Premium, padding nya diset 0

https://github.com/OpenSID/tema-natra/blob/695e6d5b005fbf873d7ff7f24ad0baf30000b64b/partials/bottom_content_left.php#L3

https://github.com/OpenSID/tema-natra/blob/85e3f2509e97226bda6d2c3bc76914cc67e0117c/partials/bottom_content_left.php#L2

https://github.com/OpenSID/tema-natra/blob/85e3f2509e97226bda6d2c3bc76914cc67e0117c/assets/css/style.css#L96

https://github.com/OpenSID/tema-natra/blob/695e6d5b005fbf873d7ff7f24ad0baf30000b64b/assets/css/style.css#L553-L560

**Comment by andifahruddinakas** [comment]
Issue ini di close sja, perubahan dari tema yg ada di umum mengikuti penggabungan rilis dari premium.

**Comment by andifahruddinakas** [comment]
> artinya .. tema natra di branch master sudah tidak digunakan lagi?

dipakai bagi yg mau menambahkan sendiri dengan perubahan. tp bawaan dari opensid umum mengikuti rilis premium yg digabungkan.
