### ISSUE TITLE
Tambah Info Nama Kecamatan dan Kabupaten dibawah nama desa

### ISSUE THREAD

**Issue by hasap86** [OpenSID/tema-natra#9]
![tambah-info-kecamatan-provinsi](https://user-images.githubusercontent.com/45263721/58069808-ee180680-7bc0-11e9-8c14-0085bbea49c1.jpg)

Supaya lebih lengkap di informasikan juga nama Kecamatan dan Kabupatennya di bawah title nama desa dengan tulisan **Kec. Arut Selatan Kab. Kotawaringin Barat**

**Comment by ariandii** [comment]
Sudah dicommit ke master.
