### ISSUE TITLE
Bug: Error di console browser untuk tema natra

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/tema-natra#94]
1. Pilih tema natra, menggunakan v22.03-premium
2. Buka web
3. Buka inspector browser
4. Perhatikan error

![image](https://user-images.githubusercontent.com/249563/156868870-8baac3f8-2373-4af2-8a1f-e81967ef1d3b.png)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/tema-natra/pull/96
